#!/command/with-contenv bash
# shellcheck shell=bash

declare -r index_version=5
declare -r data_dir="${PAPERLESS_DATA_DIR:-/usr/src/paperless/data}"
declare -r index_version_file="${data_dir}/.index_version"

if [[ (! -f "${index_version_file}") || $(<"${index_version_file}") != "$index_version" ]]; then
	echo "Search index out of date. Updating..."
	cd "${PAPERLESS_SRC_DIR}"
	s6-setuidgid paperless python3 manage.py document_index reindex --no-progress-bar
	echo ${index_version} | s6-setuidgid paperless tee "${index_version_file}" >/dev/null
fi
