#!/command/with-contenv bash
# shellcheck shell=bash

cd ${PAPERLESS_SRC_DIR}

gosu_cmd=(s6-setuidgid paperless)
if [ -n ${USER_IS_NON_ROOT} ]; then
	gosu_cmd=()
fi

exec ${gosu_cmd[@]} python3 manage.py document_consumer
