#!/command/with-contenv bash
# shellcheck shell=bash

declare -r data_dir="${PAPERLESS_DATA_DIR:-/usr/src/paperless/data}"

(
	# flock is in place to prevent multiple containers from doing migrations
	# simultaneously. This also ensures that the db is ready when the command
	# of the current container starts.
	flock 200
	echo "Apply database migrations..."
	cd "${PAPERLESS_SRC_DIR}"

	gosu_cmd=(s6-setuidgid paperless)
	if [ -n ${USER_IS_NON_ROOT} ]; then
		gosu_cmd=()
	fi
	${gosu_cmd[@]} python3 manage.py migrate --skip-checks --no-input

) 200>"${data_dir}/migration_lock"
