#!/command/with-contenv bash
# shellcheck shell=bash

echo "[init-start] paperless-ngx docker container starting..."

# Set some directories into environment for other steps to access via environment
# Sort of like variables for later
printf "/usr/src/paperless/src" > /var/run/s6/container_environment/PAPERLESS_SRC_DIR
echo $(date +%s) > /var/run/s6/container_environment/PAPERLESS_START_TIME_S

# Check if we're starting as a non-root user
if [ $(id -u) == $(id -u paperless) ]; then
	printf "true" > /var/run/s6/container_environment/USER_IS_NON_ROOT
	echo "[init-start] paperless-ngx docker container running under a user"
fi
