#!/command/with-contenv bash
# shellcheck shell=bash


if [[ -n "${PAPERLESS_ADMIN_USER}" ]]; then
	cd "${PAPERLESS_SRC_DIR}"

	gosu_cmd=(s6-setuidgid paperless)
	if [ -n ${USER_IS_NON_ROOT} ]; then
		gosu_cmd=()
	fi

	${gosu_cmd[@]} python3 manage.py manage_superuser
fi
