#!/command/with-contenv bash
# shellcheck shell=bash
declare -r end_time=$(date +%s)
declare -r start_time=${PAPERLESS_START_TIME_S}

echo "paperless-ngx docker container init completed in $(($end_time-$start_time)) seconds"
echo "Starting services"
