#!/command/with-contenv bash
# shellcheck shell=bash

echo "Checking if we should start flower..."

if [[ -n "${PAPERLESS_ENABLE_FLOWER}" ]]; then
	# Small delay to allow celery to be up first
	echo "Starting flower in 5s"
	sleep 5
	cd ${PAPERLESS_SRC_DIR}

	exec s6-setuidgid paperless /usr/local/bin/celery --app paperless flower --conf=${PAPERLESS_SRC_DIR}/paperless/flowerconfig.py
else
	echo "Not starting flower"
	# https://skarnet.org/software/s6/s6-svc.html
	exec s6-svc -Od .
fi
