#!/command/with-contenv bash
# shellcheck shell=bash

echo "Waiting for Redis to report ready"

# We use a Python script to send the Redis ping
# instead of installing redis-tools just for 1 thing
if ! python3 /usr/local/sbin/wait-for-redis.py; then
	exit 1
fi
