#!/command/with-contenv bash
# shellcheck shell=bash

# Explicitly run the Django system checks
echo "Running Django checks"

cd "${PAPERLESS_SRC_DIR}"

gosu_cmd=(s6-setuidgid paperless)
if [ -n ${USER_IS_NON_ROOT} ]; then
	gosu_cmd=()
fi

${gosu_cmd[@]} python3 manage.py check
